import { Response } from "express";
import { AuthRequest } from "../middleware/auth";
import { ChatHistoryModel } from "../models/ChatHistory";
import axios from "axios";

const AI_AGENT_URL = process.env.AI_AGENT_URL || "http://localhost:8000";

/**
 * POST /chat/message/stream
 * Body: { message: string }
 * Streams the AI's response to the client as it is generated by the Python service.
 */
export async function handleChatMessageStream(req: AuthRequest, res: Response): Promise<void> {
  try {
    const userId = req.user?._id || req.body.userId;
    if (!userId) {
      res.status(400).json({ message: "User ID is required" });
      return;
    }
    const { message } = req.body;
    if (!message || typeof message !== "string") {
      res.status(400).json({ message: "Message is required" });
      return;
    }

    // Immediately store user message
    await ChatHistoryModel.findOneAndUpdate(
      { user: userId },
      { $push: { messages: { role: "user", content: message, timestamp: new Date() } } },
      { new: true, upsert: true }
    );

    const chatHistory = await ChatHistoryModel.findOne({ user: userId });
    const contextMessages = chatHistory?.messages?.slice(-10) || [];

    // Set headers for streaming (chunked transfer)
    res.setHeader("Content-Type", "text/event-stream");
    res.setHeader("Cache-Control", "no-cache");
    res.setHeader("Connection", "keep-alive");
    res.flushHeaders?.();

    // Forward the stream from the Python AI service
    const aiResponse = await axios.post(`${AI_AGENT_URL}/task/stream`,
      { messages: contextMessages },
      {
        headers: { Authorization: req.headers.authorization || "" },
        responseType: "stream",
      }
    );

    let aiContent = "";
    aiResponse.data.on("data", (chunk: Buffer) => {
      const text = chunk.toString();
      aiContent += text;
      res.write(`data: ${JSON.stringify({ role: "ai", content: text })}\n\n`);
    });

    aiResponse.data.on("end", async () => {
      // Store the full AI message in the database
      await ChatHistoryModel.findOneAndUpdate(
        { user: userId },
        { $push: { messages: { role: "ai", content: aiContent, timestamp: new Date() } } },
        { new: true, upsert: true }
      );
      res.write("event: end\ndata: END\n\n");
      res.end();
    });

    aiResponse.data.on("error", (err: Error) => {
      res.write(`event: error\ndata: ${JSON.stringify({ error: err.message })}\n\n`);
      res.end();
    });
  } catch (error) {
    res.write(`event: error\ndata: ${JSON.stringify({ error })}\n\n`);
    res.end();
  }
}
