export const FIGMA_SCOPES = [
  "current_user:read",
  "file_comments:read",
  "file_comments:write",
  "file_content:read",
  "file_dev_resources:read",
  "file_dev_resources:write",
  "file_metadata:read",
  "file_variables:read",
  "file_variables:write",
  "file_versions:read",
  "projects:read",
  "webhooks:read",
  "webhooks:write",
];
