import { Agent } from "@openai/agents";
import * as slackTools from "../tools/slack";
import { SLACK_AGENT_PROMPT } from "../lib/prompts";

const {
  addReaction,
  inviteToChannel,
  joinChannel,
  leaveChannel,
  archiveChannel,
  deleteMessage,
  deleteScheduledMessage,
  getChannelInfo,
  getChannelMembers,
  getChannelMessages,
  getPresence,
  getScheduledMessages,
  getUnreadMessages,
  getUserInfo,
  kickFromChannel,
  listSlackChannels,
  pinMessage,
  removeReaction,
  scheduleMessage,
  sendEphemeralMessage,
  sendMessage,
  setStatus,
  unarchiveChannel,
  unpinMessage,
  updateMessage,
  updateScheduledMessage,
  uploadFile,
} = slackTools;

export const slackAgent = new Agent({
  name: "slack_agent",
  instructions: SLACK_AGENT_PROMPT,
  tools: [
    addReaction,
    inviteToChannel,
    joinChannel,
    leaveChannel,
    archiveChannel,
    deleteMessage,
    deleteScheduledMessage,
    getChannelInfo,
    getChannelMembers,
    getChannelMessages,
    getPresence,
    getScheduledMessages,
    getUnreadMessages,
    getUserInfo,
    kickFromChannel,
    listSlackChannels,
    pinMessage,
    removeReaction,
    scheduleMessage,
    sendEphemeralMessage,
    sendMessage,
    setStatus,
    unarchiveChannel,
    unpinMessage,
    updateMessage,
    updateScheduledMessage,
    uploadFile,
  ],
});
